# Generated by Django 4.1.7 on 2023-06-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradas',
            options={},
        ),
    ]
