# Generated by Django 4.1.7 on 2023-06-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_cores_options'),
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidas',
            name='preco',
        ),
        migrations.AlterField(
            model_name='saidas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produtos', verbose_name='Produto'),
        ),
    ]
